parameters:
  data_dim: &data_dim 384
  num_nodes: &num_nodes 190091


seed: 42

data_parameters:
  dataset_type: coview-mdm
  to_undirected: false
  add_self_loops_and_remove_duplicate_edges: false
  remove_duplicate_edges: false
  train_data_loader_parameters:
    data_loader_type: link_loader
    batch_size: 1048576
    mask_loss_edges: false
    max_rejection_sampling_iterations: 2
    negative_sampling_ratio: 0.5
    on_device: false
    use_precomputed_negatives: true
    precomputed_negatives_sampling_ratio: 1.0
  val_data_loader_parameters:
    data_loader_type: link_loader
    batch_size: 131072
    negative_sampling_ratio: 0.5
    on_device: false
  test_data_loader_parameters:
    data_loader_type: link_loader
    batch_size: 131072
    negative_sampling_ratio: 0.5
    on_device: false
    use_val_edges_as_input: false

model_parameters:
  task_type: link_prediction
  architecture_parameters:
      architecture_type: gcn
      input_dim: *data_dim
      hidden_dim: 64
      output_dim: 128
      num_layers: 2
      dropout: 0.0
      use_input_projection: false
      use_output_projection: false
      use_residual: false
      use_layer_norm: false
      conv_parameters:
        cached: true

  link_predictor_parameters:
    link_predictor_type: hadamard_mlp
    parameters:
      dropout: 0.0
      num_layers: 3
      use_residual: true
      use_layer_norm: false

  loss:
      loss_type: bce_with_logits_loss

  metrics:
    - metric_type: hit_rate
      display_name: hit_rate@50
      parameters:
        k: 50
    - metric_type: hit_rate
      display_name: hit_rate@100
      parameters:
        k: 100
    - metric_type: binary_accuracy
      display_name: accuracy

  optimizer:
    optimizer_type: adam
    parameters:
      lr: 0.001
      weight_decay: 0

callbacks:
    - callback_type: early_stopping
      parameters:
        monitor: val/hit_rate@50
        patience: 6
        mode: "max"

wandb_logger_parameters:
  entity: "neilbraunheinrich-national-university-of-singapore"
  project: "fast_gnn_benchmark"
  reinit: true

compilation_parameters:
  use_compiled_torch: false
  full_graph: false

trainer_config:
  max_epochs: 400
  log_every_n_steps: 10
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 5
